-- ============================================================================
-- RESELLER ENGAGEMENT (CREDIT BACK) - DATABASE SCHEMA
-- ============================================================================
-- Purpose: DDL for all SALR_E_ prefixed tables for the Reseller Engagement system
-- Database: Oracle
-- ERP System: Spine (existing tables not modified here)
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. CREDIT BACK RULES & BRACKETS
-- ----------------------------------------------------------------------------

-- Credit Back Rule Master Table
CREATE TABLE SALR_E_CREDIT_BACK_RULE (
  RULE_ID            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  RULE_NAME          VARCHAR2(200) NOT NULL,
  VALID_FROM         DATE NOT NULL,
  VALID_TO           DATE NOT NULL,
  MODE_CODE          VARCHAR2(20) NOT NULL, -- 'NEXT_ORDER', 'NEXT_WITHIN', 'ANYTIME'
  IS_ACTIVE          CHAR(1) DEFAULT 'Y' CHECK (IS_ACTIVE IN ('Y','N')),
  CREATED_BY         VARCHAR2(100),
  CREATED_AT         DATE DEFAULT SYSDATE,
  UPDATED_BY         VARCHAR2(100),
  UPDATED_AT         DATE,
  CONSTRAINT SALR_E_CBR_MODE_CHK CHECK (MODE_CODE IN ('NEXT_ORDER', 'NEXT_WITHIN', 'ANYTIME'))
);

-- Create index on active rules for faster lookups
CREATE INDEX SALR_E_CBR_ACTIVE_IDX ON SALR_E_CREDIT_BACK_RULE (IS_ACTIVE, VALID_FROM, VALID_TO);

COMMENT ON TABLE SALR_E_CREDIT_BACK_RULE IS 'Master table for Credit Back rules with validity periods and modes';
COMMENT ON COLUMN SALR_E_CREDIT_BACK_RULE.MODE_CODE IS 'Application mode: NEXT_ORDER (next order only), NEXT_WITHIN (next order within timeframe), ANYTIME (any order in window)';

-- Credit Back Rule Brackets - defines percentage tiers per rule
CREATE TABLE SALR_E_CREDIT_BACK_RULE_BRACKET (
  BRACKET_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  RULE_ID            NUMBER NOT NULL REFERENCES SALR_E_CREDIT_BACK_RULE (RULE_ID) ON DELETE CASCADE,
  MIN_SALES_AMOUNT   NUMBER(18,2) NOT NULL,
  MAX_SALES_AMOUNT   NUMBER(18,2), -- NULL means "no upper limit"
  CREDIT_PERCENT     NUMBER(5,2) NOT NULL,
  PRIORITY_NO        NUMBER(5) DEFAULT 1,
  CONSTRAINT SALR_E_CB_BRK_UK UNIQUE (RULE_ID, MIN_SALES_AMOUNT),
  CONSTRAINT SALR_E_CB_BRK_AMOUNT_CHK CHECK (MAX_SALES_AMOUNT IS NULL OR MAX_SALES_AMOUNT > MIN_SALES_AMOUNT),
  CONSTRAINT SALR_E_CB_BRK_PERCENT_CHK CHECK (CREDIT_PERCENT >= 0 AND CREDIT_PERCENT <= 100)
);

CREATE INDEX SALR_E_CBB_RULE_IDX ON SALR_E_CREDIT_BACK_RULE_BRACKET (RULE_ID);

COMMENT ON TABLE SALR_E_CREDIT_BACK_RULE_BRACKET IS 'Defines percentage brackets for each Credit Back rule (e.g., 0-5000=1%, 5000-10000=2%)';

-- ----------------------------------------------------------------------------
-- 2. CREDIT BACK LEDGER
-- ----------------------------------------------------------------------------

-- Credit Back Ledger - tracks earned, redeemed, and expired credits
CREATE TABLE SALR_E_CREDIT_BACK_LEDGER (
  LEDGER_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  RESELLER_ID        NUMBER NOT NULL, -- references ERP reseller master (SPINE_RESELLER)
  ORDER_ID           NUMBER,         -- references ERP order/invoice (SPINE_SALES_ORDER or SPINE_INVOICE)
  RULE_ID            NUMBER REFERENCES SALR_E_CREDIT_BACK_RULE (RULE_ID),
  PROMO_ID           NUMBER,         -- optional: link to SALR_E_PROMO
  CREDIT_AMOUNT      NUMBER(18,2) NOT NULL,
  STATUS_CODE        VARCHAR2(20) NOT NULL, -- 'EARNED','REDEEMED','EXPIRED'
  EARNED_AT          DATE DEFAULT SYSDATE,
  REDEEMED_AT        DATE,
  EXPIRY_DATE        DATE,
  REMARKS            VARCHAR2(500),
  CREATED_AT         DATE DEFAULT SYSDATE,
  CREATED_BY         VARCHAR2(100),
  CONSTRAINT SALR_E_CBL_STATUS_CHK CHECK (STATUS_CODE IN ('EARNED','REDEEMED','EXPIRED'))
);

CREATE INDEX SALR_E_CBL_RESELLER_IDX ON SALR_E_CREDIT_BACK_LEDGER (RESELLER_ID, STATUS_CODE);
CREATE INDEX SALR_E_CBL_ORDER_IDX ON SALR_E_CREDIT_BACK_LEDGER (ORDER_ID);
CREATE INDEX SALR_E_CBL_STATUS_IDX ON SALR_E_CREDIT_BACK_LEDGER (STATUS_CODE, EXPIRY_DATE);

COMMENT ON TABLE SALR_E_CREDIT_BACK_LEDGER IS 'Ledger of all Credit Back transactions - earned, redeemed, and expired';
COMMENT ON COLUMN SALR_E_CREDIT_BACK_LEDGER.STATUS_CODE IS 'EARNED (available), REDEEMED (used), EXPIRED (no longer valid)';

-- ----------------------------------------------------------------------------
-- 3. PROMOTIONS & PROMO SKUs
-- ----------------------------------------------------------------------------

-- Promotions Master Table
CREATE TABLE SALR_E_PROMO (
  PROMO_ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  PROMO_NAME         VARCHAR2(200) NOT NULL,
  DESCRIPTION        VARCHAR2(1000),
  START_DT           DATE NOT NULL,
  END_DT             DATE NOT NULL,
  TARGET_SEGMENT     VARCHAR2(50), -- e.g. 'DORMANT','ACTIVE','ALL'
  STATUS_CODE        VARCHAR2(20) DEFAULT 'DRAFT', -- 'DRAFT','ACTIVE','EXPIRED','CANCELLED'
  CREATED_BY         VARCHAR2(100),
  CREATED_AT         DATE DEFAULT SYSDATE,
  UPDATED_BY         VARCHAR2(100),
  UPDATED_AT         DATE,
  CONSTRAINT SALR_E_PROMO_DATE_CHK CHECK (END_DT >= START_DT),
  CONSTRAINT SALR_E_PROMO_STATUS_CHK CHECK (STATUS_CODE IN ('DRAFT','ACTIVE','EXPIRED','CANCELLED'))
);

CREATE INDEX SALR_E_PROMO_STATUS_IDX ON SALR_E_PROMO (STATUS_CODE, START_DT, END_DT);
CREATE INDEX SALR_E_PROMO_SEGMENT_IDX ON SALR_E_PROMO (TARGET_SEGMENT);

COMMENT ON TABLE SALR_E_PROMO IS 'Master table for promotional campaigns';
COMMENT ON COLUMN SALR_E_PROMO.TARGET_SEGMENT IS 'Target reseller segment: DORMANT (inactive), ACTIVE, ALL';

-- Promotion SKU Details - links SKUs to promotions with pricing
CREATE TABLE SALR_E_PROMO_SKU (
  PROMO_SKU_ID       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  PROMO_ID           NUMBER NOT NULL REFERENCES SALR_E_PROMO (PROMO_ID) ON DELETE CASCADE,
  SKU_ID             NUMBER NOT NULL, -- ERP SKU ID (references SPINE_SKU)
  SKU_CODE           VARCHAR2(100),   -- denormalized for quick access
  SKU_NAME           VARCHAR2(500),   -- denormalized for quick access
  BEFORE_PRICE       NUMBER(18,4),
  OFFER_PRICE        NUMBER(18,4),
  DISCOUNT_PERCENT   NUMBER(5,2),     -- calculated: (BEFORE_PRICE - OFFER_PRICE) / BEFORE_PRICE * 100
  ASSET_URL          VARCHAR2(500),   -- image file/url placeholder for offer card
  CAPTION_EN         CLOB,            -- English WhatsApp caption
  CAPTION_AR         CLOB,            -- Arabic WhatsApp caption
  CREATED_AT         DATE DEFAULT SYSDATE
);

CREATE INDEX SALR_E_PROMO_SKU_PROMO_IDX ON SALR_E_PROMO_SKU (PROMO_ID);
CREATE INDEX SALR_E_PROMO_SKU_SKU_IDX ON SALR_E_PROMO_SKU (SKU_ID);

COMMENT ON TABLE SALR_E_PROMO_SKU IS 'SKU-level details for each promotion including pricing and WhatsApp templates';

-- ----------------------------------------------------------------------------
-- 4. WHATSAPP MESSAGE LOGS
-- ----------------------------------------------------------------------------

-- WhatsApp Message Log - all inbound, outbound, and internal alert messages
CREATE TABLE SALR_E_WHATSAPP_MESSAGE (
  MSG_ID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  RESELLER_ID        NUMBER,         -- NULL for internal alerts
  PROMO_ID           NUMBER REFERENCES SALR_E_PROMO (PROMO_ID),
  DIRECTION_CODE     VARCHAR2(20) NOT NULL, -- 'OUTBOUND','INBOUND','INTERNAL_ALERT'
  MESSAGE_TYPE       VARCHAR2(50), -- 'PROMO','AVAILABILITY','ORDER','CREDIT','PROFILE','INTERNAL_ALERT','OTHER'
  TEMPLATE_ID        VARCHAR2(100),
  PHONE_NUMBER       VARCHAR2(30),   -- WhatsApp phone number (E.164 format recommended)
  MESSAGE_BODY       CLOB,           -- actual message content
  STATUS_CODE        VARCHAR2(20), -- 'QUEUED','SENT','DELIVERED','READ','REPLIED','FAILED'
  SOURCE_CHANNEL     VARCHAR2(50), -- 'WHATSAPP_API','SIMULATION','MANUAL'
  SENT_AT            DATE,
  DELIVERED_AT       DATE,
  READ_AT            DATE,
  REPLIED_AT         DATE,
  FAILED_AT          DATE,
  ERROR_MESSAGE      VARCHAR2(1000),
  EXTERNAL_MSG_ID    VARCHAR2(200), -- WhatsApp API message ID
  RAW_PAYLOAD        CLOB,           -- raw JSON payload from/to WhatsApp API
  CREATED_AT         DATE DEFAULT SYSDATE,
  CONSTRAINT SALR_E_WM_DIR_CHK CHECK (DIRECTION_CODE IN ('OUTBOUND','INBOUND','INTERNAL_ALERT')),
  CONSTRAINT SALR_E_WM_STATUS_CHK CHECK (STATUS_CODE IN ('QUEUED','SENT','DELIVERED','READ','REPLIED','FAILED'))
);

CREATE INDEX SALR_E_WM_RESELLER_IDX ON SALR_E_WHATSAPP_MESSAGE (RESELLER_ID, CREATED_AT DESC);
CREATE INDEX SALR_E_WM_PROMO_IDX ON SALR_E_WHATSAPP_MESSAGE (PROMO_ID);
CREATE INDEX SALR_E_WM_DIRECTION_IDX ON SALR_E_WHATSAPP_MESSAGE (DIRECTION_CODE, STATUS_CODE);
CREATE INDEX SALR_E_WM_STATUS_IDX ON SALR_E_WHATSAPP_MESSAGE (STATUS_CODE, CREATED_AT DESC);

COMMENT ON TABLE SALR_E_WHATSAPP_MESSAGE IS 'Complete log of all WhatsApp messages: outbound promos, inbound queries, internal alerts';
COMMENT ON COLUMN SALR_E_WHATSAPP_MESSAGE.DIRECTION_CODE IS 'OUTBOUND (to reseller), INBOUND (from reseller), INTERNAL_ALERT (to Sedar team)';

-- ----------------------------------------------------------------------------
-- 5. RESELLER REQUESTS
-- ----------------------------------------------------------------------------

-- Reseller Requests - tracks orders, availability checks, and other requests from resellers
CREATE TABLE SALR_E_RESELLER_REQUEST (
  REQUEST_ID         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  RESELLER_ID        NUMBER NOT NULL, -- references SPINE_RESELLER
  REQUEST_TYPE       VARCHAR2(30) NOT NULL, -- 'ORDER','AVAILABILITY','PROFILE','OTHER'
  PAYLOAD_JSON       CLOB, -- store width/height, item code, quantity, etc. as JSON
  PARSED_SKU_CODE    VARCHAR2(100), -- extracted SKU code for indexing
  ROUTED_TO_USER_ID  VARCHAR2(100), -- account manager/internal user code
  STATUS_CODE        VARCHAR2(20) DEFAULT 'OPEN', -- 'OPEN','IN_PROGRESS','CLOSED','CANCELLED'
  PRIORITY_LEVEL     VARCHAR2(20) DEFAULT 'NORMAL', -- 'LOW','NORMAL','HIGH','URGENT'
  RESPONSE_TEXT      CLOB,          -- response sent back to reseller
  CREATED_AT         DATE DEFAULT SYSDATE,
  UPDATED_AT         DATE,
  CLOSED_AT          DATE,
  CONSTRAINT SALR_E_RR_TYPE_CHK CHECK (REQUEST_TYPE IN ('ORDER','AVAILABILITY','PROFILE','CREDIT','OTHER')),
  CONSTRAINT SALR_E_RR_STATUS_CHK CHECK (STATUS_CODE IN ('OPEN','IN_PROGRESS','CLOSED','CANCELLED'))
);

CREATE INDEX SALR_E_RR_RESELLER_IDX ON SALR_E_RESELLER_REQUEST (RESELLER_ID, CREATED_AT DESC);
CREATE INDEX SALR_E_RR_STATUS_IDX ON SALR_E_RESELLER_REQUEST (STATUS_CODE, CREATED_AT);
CREATE INDEX SALR_E_RR_ROUTED_IDX ON SALR_E_RESELLER_REQUEST (ROUTED_TO_USER_ID, STATUS_CODE);

COMMENT ON TABLE SALR_E_RESELLER_REQUEST IS 'Tracks all requests from resellers via WhatsApp (orders, availability checks, etc.)';
COMMENT ON COLUMN SALR_E_RESELLER_REQUEST.PAYLOAD_JSON IS 'JSON payload with request details (e.g., {"skuCode":"BL-001","width":100,"height":150})';

-- ----------------------------------------------------------------------------
-- 6. ADMIN CONFIGURATION
-- ----------------------------------------------------------------------------

-- Admin Configuration - key-value store for system settings
CREATE TABLE SALR_E_ADMIN_CONFIG (
  CONFIG_ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  CONFIG_KEY         VARCHAR2(100) NOT NULL UNIQUE,
  CONFIG_VALUE       VARCHAR2(2000),
  CONFIG_TYPE        VARCHAR2(20) DEFAULT 'STRING', -- 'STRING','NUMBER','BOOLEAN','JSON'
  DESCRIPTION        VARCHAR2(500),
  UPDATED_BY         VARCHAR2(100),
  UPDATED_AT         DATE DEFAULT SYSDATE,
  CONSTRAINT SALR_E_AC_TYPE_CHK CHECK (CONFIG_TYPE IN ('STRING','NUMBER','BOOLEAN','JSON'))
);

CREATE UNIQUE INDEX SALR_E_AC_KEY_UK ON SALR_E_ADMIN_CONFIG (CONFIG_KEY);

COMMENT ON TABLE SALR_E_ADMIN_CONFIG IS 'System-wide configuration settings (e.g., thresholds, frequency limits)';

-- Insert default configurations
INSERT INTO SALR_E_ADMIN_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION) VALUES ('RESLLR_DORMANT_DAYS', '60', 'NUMBER', 'Days without order to consider reseller dormant');
INSERT INTO SALR_E_ADMIN_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION) VALUES ('RESLLR_CHURNED_DAYS', '90', 'NUMBER', 'Days without order to consider reseller churned');
INSERT INTO SALR_E_ADMIN_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION) VALUES ('PROMO_MAX_PER_WEEK', '2', 'NUMBER', 'Maximum promotions per reseller per week');
INSERT INTO SALR_E_ADMIN_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION) VALUES ('CREDIT_EXPIRY_DAYS', '180', 'NUMBER', 'Days until earned credit expires');
INSERT INTO SALR_E_ADMIN_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION) VALUES ('WHATSAPP_ENABLED', 'false', 'BOOLEAN', 'Enable/disable actual WhatsApp API integration');
INSERT INTO SALR_E_ADMIN_CONFIG (CONFIG_KEY, CONFIG_VALUE, CONFIG_TYPE, DESCRIPTION) VALUES ('PROMO_TARGET_SEGMENT_DEFAULT', 'DORMANT', 'STRING', 'Default target segment for new promotions');

COMMIT;

-- ----------------------------------------------------------------------------
-- 7. WHATSAPP OTP SESSIONS
-- ----------------------------------------------------------------------------

-- WhatsApp OTP Session - for secure profile link access
CREATE TABLE SALR_E_WHATSAPP_OTP_SESSION (
  SESSION_ID         VARCHAR2(64) PRIMARY KEY,
  RESELLER_ID        NUMBER NOT NULL, -- references SPINE_RESELLER
  WHATSAPP_NUMBER    VARCHAR2(30) NOT NULL,
  OTP_HASH           VARCHAR2(200) NOT NULL, -- bcrypt/sha256 hash of OTP
  EXPIRES_AT         DATE NOT NULL,
  VERIFIED_AT        DATE,
  VERIFICATION_COUNT NUMBER(2) DEFAULT 0, -- track failed attempts
  CREATED_AT         DATE DEFAULT SYSDATE,
  CONSTRAINT SALR_E_OTP_VERIFY_CHK CHECK (VERIFICATION_COUNT <= 5)
);

CREATE INDEX SALR_E_OTP_RESELLER_IDX ON SALR_E_WHATSAPP_OTP_SESSION (RESELLER_ID);
CREATE INDEX SALR_E_OTP_EXPIRES_IDX ON SALR_E_WHATSAPP_OTP_SESSION (EXPIRES_AT);

COMMENT ON TABLE SALR_E_WHATSAPP_OTP_SESSION IS 'One-time password sessions for secure reseller profile access via WhatsApp';

-- ----------------------------------------------------------------------------
-- 8. AUDIT LOG (OPTIONAL - for tracking all admin actions)
-- ----------------------------------------------------------------------------

-- Audit Log - track all admin actions for compliance
CREATE TABLE SALR_E_AUDIT_LOG (
  AUDIT_ID           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  USER_ID            VARCHAR2(100) NOT NULL,
  ACTION_TYPE        VARCHAR2(50) NOT NULL, -- 'CREATE','UPDATE','DELETE','SEND_PROMO','ACTIVATE_RULE', etc.
  ENTITY_TYPE        VARCHAR2(50), -- 'PROMO','RULE','CONFIG','RESELLER_REQUEST', etc.
  ENTITY_ID          NUMBER,
  OLD_VALUE          CLOB,
  NEW_VALUE          CLOB,
  IP_ADDRESS         VARCHAR2(45),
  USER_AGENT         VARCHAR2(500),
  CREATED_AT         DATE DEFAULT SYSDATE
);

CREATE INDEX SALR_E_AL_USER_IDX ON SALR_E_AUDIT_LOG (USER_ID, CREATED_AT DESC);
CREATE INDEX SALR_E_AL_ENTITY_IDX ON SALR_E_AUDIT_LOG (ENTITY_TYPE, ENTITY_ID);

COMMENT ON TABLE SALR_E_AUDIT_LOG IS 'Audit trail of all admin actions for compliance and debugging';

-- ============================================================================
-- VIEWS (OPTIONAL - for common queries)
-- ============================================================================

-- View: Active Credit Back Rules with Bracket Count
CREATE OR REPLACE VIEW SALR_E_V_ACTIVE_RULES AS
SELECT
  r.RULE_ID,
  r.RULE_NAME,
  r.VALID_FROM,
  r.VALID_TO,
  r.MODE_CODE,
  r.IS_ACTIVE,
  COUNT(b.BRACKET_ID) AS BRACKET_COUNT,
  r.CREATED_AT,
  r.UPDATED_AT
FROM SALR_E_CREDIT_BACK_RULE r
LEFT JOIN SALR_E_CREDIT_BACK_RULE_BRACKET b ON r.RULE_ID = b.RULE_ID
WHERE r.IS_ACTIVE = 'Y'
  AND r.VALID_TO >= SYSDATE
GROUP BY r.RULE_ID, r.RULE_NAME, r.VALID_FROM, r.VALID_TO, r.MODE_CODE, r.IS_ACTIVE, r.CREATED_AT, r.UPDATED_AT;

-- View: Reseller Credit Balance Summary
CREATE OR REPLACE VIEW SALR_E_V_RESELLER_CREDIT_BALANCE AS
SELECT
  RESELLER_ID,
  SUM(CASE WHEN STATUS_CODE = 'EARNED' THEN CREDIT_AMOUNT ELSE 0 END) AS TOTAL_EARNED,
  SUM(CASE WHEN STATUS_CODE = 'REDEEMED' THEN CREDIT_AMOUNT ELSE 0 END) AS TOTAL_REDEEMED,
  SUM(CASE WHEN STATUS_CODE = 'EXPIRED' THEN CREDIT_AMOUNT ELSE 0 END) AS TOTAL_EXPIRED,
  SUM(CASE WHEN STATUS_CODE = 'EARNED' THEN CREDIT_AMOUNT ELSE 0 END)
    - SUM(CASE WHEN STATUS_CODE = 'REDEEMED' THEN CREDIT_AMOUNT ELSE 0 END) AS AVAILABLE_BALANCE,
  MAX(EARNED_AT) AS LAST_EARNED_DATE
FROM SALR_E_CREDIT_BACK_LEDGER
GROUP BY RESELLER_ID;

-- View: Promotion Performance Summary
CREATE OR REPLACE VIEW SALR_E_V_PROMO_PERFORMANCE AS
SELECT
  p.PROMO_ID,
  p.PROMO_NAME,
  p.START_DT,
  p.END_DT,
  p.STATUS_CODE,
  COUNT(DISTINCT ps.PROMO_SKU_ID) AS SKU_COUNT,
  COUNT(DISTINCT wm.RESELLER_ID) AS RESELLER_COUNT,
  SUM(CASE WHEN wm.STATUS_CODE = 'SENT' THEN 1 ELSE 0 END) AS SENT_COUNT,
  SUM(CASE WHEN wm.STATUS_CODE = 'DELIVERED' THEN 1 ELSE 0 END) AS DELIVERED_COUNT,
  SUM(CASE WHEN wm.STATUS_CODE = 'READ' THEN 1 ELSE 0 END) AS READ_COUNT,
  SUM(CASE WHEN wm.STATUS_CODE = 'REPLIED' THEN 1 ELSE 0 END) AS REPLIED_COUNT
FROM SALR_E_PROMO p
LEFT JOIN SALR_E_PROMO_SKU ps ON p.PROMO_ID = ps.PROMO_ID
LEFT JOIN SALR_E_WHATSAPP_MESSAGE wm ON p.PROMO_ID = wm.PROMO_ID AND wm.DIRECTION_CODE = 'OUTBOUND'
GROUP BY p.PROMO_ID, p.PROMO_NAME, p.START_DT, p.END_DT, p.STATUS_CODE;

-- ============================================================================
-- SEQUENCES (if not using IDENTITY columns in older Oracle versions)
-- ============================================================================
-- Note: Oracle 12c+ supports IDENTITY columns as used above
-- For Oracle 11g or earlier, create sequences manually:
-- CREATE SEQUENCE SALR_E_CBR_SEQ START WITH 1 INCREMENT BY 1;
-- etc.

-- ============================================================================
-- GRANTS (adjust based on your security model)
-- ============================================================================
-- Example: GRANT SELECT, INSERT, UPDATE, DELETE ON SALR_E_CREDIT_BACK_RULE TO APP_USER;

-- ============================================================================
-- COMMENTS & DOCUMENTATION
-- ============================================================================

COMMENT ON TABLE SALR_E_CREDIT_BACK_RULE IS 'Credit Back rules with validity periods and application modes';
COMMENT ON TABLE SALR_E_CREDIT_BACK_RULE_BRACKET IS 'Percentage brackets for each Credit Back rule';
COMMENT ON TABLE SALR_E_CREDIT_BACK_LEDGER IS 'Ledger of all Credit Back transactions';
COMMENT ON TABLE SALR_E_PROMO IS 'Master table for promotional campaigns';
COMMENT ON TABLE SALR_E_PROMO_SKU IS 'SKU-level details for promotions';
COMMENT ON TABLE SALR_E_WHATSAPP_MESSAGE IS 'Complete log of all WhatsApp messages';
COMMENT ON TABLE SALR_E_RESELLER_REQUEST IS 'Tracks all requests from resellers';
COMMENT ON TABLE SALR_E_ADMIN_CONFIG IS 'System-wide configuration settings';
COMMENT ON TABLE SALR_E_WHATSAPP_OTP_SESSION IS 'One-time password sessions for secure profile access';
COMMENT ON TABLE SALR_E_AUDIT_LOG IS 'Audit trail of all admin actions';

-- ============================================================================
-- END OF SCHEMA
-- ============================================================================
